### ISSUE TITLE
Starlette errors hidden behind InternalServerErrors and HEAD requests not allowed

### ISSUE THREAD

**Issue by Tobi696** [significa/app-distribution-server#27]
I get a 405 method not allowed error when trying to install on iOS and no error is displayed on the phone, but download is stopped.
Here are my logs:
```
INFO:     192.168.65.1:41908 - "GET /static/logo.svg HTTP/1.1" 200 OK
INFO:     192.168.65.1:41910 - "GET /get/a971e20f-511e-4f67-92a9-063958f2a89e/app.plist HTTP/1.1" 200 OK
2024-11-15 23:11:26 ERROR Unexpected StarletteHTTPException: 405: Method Not Allowed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 746, in app
    await partial.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 283, in handle
    raise HTTPException(status_code=405, headers=headers)
starlette.exceptions.HTTPException: 405: Method Not Allowed
INFO:     192.168.65.1:41911 - "HEAD /get/a971e20f-511e-4f67-92a9-063958f2a89e/app.ipa HTTP/1.1" 500 Internal Server Error
2024-11-15 23:11:28 ERROR Unexpected StarletteHTTPException: 405: Method Not Allowed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 746, in app
    await partial.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 283, in handle
    raise HTTPException(status_code=405, headers=headers)
starlette.exceptions.HTTPException: 405: Method Not Allowed
```

I'm trying a to download and install an ipa generated with `flutter build ipa`

**Comment by bwomsm1** [comment]
@Tobi696 did you manage to solve this problem?

**Comment by tofran** [comment]
Thank you for the report. Allowing the HEAD method should solve this.
